# .github/workflows/build.yml
name: Build

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Run Build with Version
      run: echo "${{ inputs.version }}" > version.txt

    - name: Save Version Artifact
      uses: actions/upload-artifact@v3
      with:
        name: version
        path: version.txt
