# .github/workflows/build.yml
name: Build

on:
  workflow_call: # This allows the workflow to be called by other workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Run Build
      run: echo "Building..."

    - name: Save Version Artifact
      uses: actions/upload-artifact@v3
      with:
        name: version
        path: version.txt
