# .github/workflows/build.yml
name: Build

on:
  workflow_call: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run the Python script
      run: python hello.py

    - name: Save version artifact
      if: always() # Save artifact even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: version
        path: version.txt # Path to the file where the version is saved
