name: Download and Upload to Box

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifact from Previous Workflow
        uses: actions/download-artifact@v3
        with:
          name: java-lambda-jar  # Name of the artifact uploaded in the previous workflow
          path: ./artifact  # Path to save the downloaded artifact

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install "boxsdk[jwt]"

      - name: Generate Box Access Token
        run: |
          echo "${{ secrets.BOX_JWT_CONFIG }}" | base64 --decode | jq > config.json
          ACCESS_TOKEN=$(python3 - <<EOF
          from boxsdk import JWTAuth
          auth = JWTAuth.from_settings_file('config.json')
          access_token = auth.authenticate_instance()
          print(access_token)
          EOF
          )
          echo "BOX_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Upload Artifact to Box
        env:
          BOX_ACCESS_TOKEN: ${{ env.BOX_ACCESS_TOKEN }}
          BOX_FOLDER_ID: '0'  # Replace with your actual Box folder ID
        run: |
          for file in ./artifact/*; do
            curl -X POST "https://upload.box.com/api/2.0/files/content" \
              -H "authorization: Bearer $BOX_ACCESS_TOKEN" \
              -H "content-type: multipart/form-data" \
              -F "attributes={\"name\":\"$(basename "$file")\", \"parent\":{\"id\":\"$BOX_FOLDER_ID\"}}" \
              -F file=@$file
          done

      - name: List Files in the Folder
        env:
          BOX_ACCESS_TOKEN: ${{ env.BOX_ACCESS_TOKEN }}
        run: |
          FOLDER_ID="0"  # Replace with your actual folder ID if not the root
          RESPONSE=$(curl -X GET https://api.box.com/2.0/folders/$FOLDER_ID/items \
            -H "Authorization: Bearer $BOX_ACCESS_TOKEN" \
            -H "Content-Type: application/json")
          echo "Files in Folder:"
          echo $RESPONSE | jq -r '.entries[] | select(.type == "file") | .name'
