name: Download and Upload to Box

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: java-lambda-jar
          path: ./artifact

      - name: Install Python and dependencies for Box SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install "boxsdk[jwt]"

      - name: Generate Box Access Token
        run: |
          echo "${{ secrets.BOX_JWT_CONFIG }}" | base64 --decode | jq > config.json
          ACCESS_TOKEN=$(python3 - <<EOF
          from boxsdk import JWTAuth
          auth = JWTAuth.from_settings_file('config.json')
          access_token = auth.authenticate_instance()
          print(access_token)
          EOF
          )
          echo "BOX_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Upload Artifact to Box
        env:
          BOX_ACCESS_TOKEN: ${{ env.BOX_ACCESS_TOKEN }}
          BOX_FOLDER_ID: '0'
        run: |
          FILE_PATH=$(find ./artifact -type f -name '*.jar')
          echo "Uploading file $FILE_PATH to Box"
          curl -X POST "https://upload.box.com/api/2.0/files/content" \
            -H "Authorization: Bearer $BOX_ACCESS_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "attributes={\"name\":\"$(basename $FILE_PATH)\", \"parent\":{\"id\":\"$BOX_FOLDER_ID\"}}" \
            -F "file=@$FILE_PATH"
