# .github/workflows/promote.yml
name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  post-promote:
    runs-on: ubuntu-latest
    needs: call-build  # Ensure the build job has finished

    steps:
    - name: Download version artifact
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./  # Directory where the artifact will be downloaded

    - name: Display the version from artifact
      run: |
        if [ -f version.txt ]; then
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        else
          echo "VERSION=unknown" >> $GITHUB_ENV
        fi

    - name: Show the version
      run: echo "Promoting with version: ${{ env.VERSION }}"

    - name: Run post-promotion tasks
      run: echo "Running post-promotion tasks with version: ${{ env.VERSION }}"
