# .github/workflows/promote.yml
name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: false
        default: '' # Default to empty; will use artifact version if not provided

jobs:
  promote:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  post-promote:
    runs-on: ubuntu-latest
    needs: promote

    steps:
    - name: Display the version
      run: |
        echo "Promoting with version: ${{ github.event.inputs.version }}"
    - name: Run post-promotion tasks
      run: |
        echo "Running post-promotion tasks with version: ${{ github.event.inputs.version }}"
