# .github/workflows/promote.yml
name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: false
        default: '' # Default is empty; will use artifact version if not provided

jobs:
  promote:
    uses: ./.github/workflows/build.yml # Call the build workflow
    with:
      version: ${{ github.event.inputs.version }} # Pass version input if required

    outputs:
      version: ${{ steps.set_version.outputs.version }} # Define outputs if needed

    # Additional steps after calling the build workflow
    runs-on: ubuntu-latest
    needs: promote # Ensure build has finished
    steps:
    - name: Download version artifact
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./

    - name: Set default version from artifact
      id: set_version
      run: |
        if [ -f version.txt ]; then
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=unknown" >> $GITHUB_ENV
        fi

    - name: Display the version
      run: |
        VERSION=${{ github.event.inputs.version || env.VERSION }}
        echo "Promoting with version: $VERSION"

    - name: Run post-promotion tasks
      run: |
        VERSION=${{ github.event.inputs.version || env.VERSION }}
        echo "Running post-promotion tasks with version: $VERSION"
