# .github/workflows/promote.yml
name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  post-promote:
    runs-on: ubuntu-latest
    needs: call-build  # Ensure the build job has finished

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download version artifact
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./  # Downloads artifact to the current working directory

    - name: Display the previous and new version
      run: |
        echo "Previous version:"
        cat version.txt
        echo "New version: ${{ github.event.inputs.version }}"
        echo "${{ github.event.inputs.version }}" > version.txt
        echo "Updated version:"
        cat version.txt
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Show the version
      run: echo "Promoting with version:${{ env.VERSION }}"

    - name: Run post-promotion tasks
      run: echo "Running post-promotion tasks with version:${{ env.VERSION }}"

    - name: Commit updated version.txt
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add version.txt
        git commit -m "Update version.txt with new version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

