name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  promote:
    uses: ./.github/workflows/build.yml  # Corrected the path to the build workflow

  post-promote:
    runs-on: ubuntu-latest
    needs: promote

    steps:
    - name: Display the version
      run: |
        echo "Promoting with version: ${{ github.event.inputs.version }}"

    - name: Run post-promotion tasks
      run: |
        echo "Running post-promotion tasks with version: ${{ github.event.inputs.version }}"
