# .github/workflows/promote.yml
name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  post-promote:
    runs-on: ubuntu-latest
    needs: call-build  # Ensure the build job has finished

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download version artifact
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./  # Downloads artifact to the current working directory

    - name: Check if the version is the same
      id: check_version
      run: |
        current_version=$(cat version.txt)
        echo "Previous version: $current_version"
        if [ "$current_version" = "${{ github.event.inputs.version }}" ]; then
          echo "Same version detected, skipping update."
          echo "SKIP_UPDATE=true" >> $GITHUB_ENV
        else
          echo "New version detected."
          echo "${{ github.event.inputs.version }}" > version.txt
          echo "SKIP_UPDATE=false" >> $GITHUB_ENV

    - name: Commit and push updated version.txt
      if: env.SKIP_UPDATE == 'false'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add version.txt
        git commit -m "Update version.txt with new version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT secret for authentication

    - name: Show the version
      if: env.SKIP_UPDATE == 'false'
      run: echo "Promoting with version: ${{ github.event.inputs.version }}"

    - name: Skip promotion
      if: env.SKIP_UPDATE == 'true'
      run: echo "Skipping promotion as the version is the same."
