name: Ship JAR File to Box

on:
  workflow_dispatch: 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Box SDK
        run: npm install box-node-sdk

      - name: Upload JAR file to Box
        env:
          BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
          BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
          BOX_DEVELOPER_TOKEN: ${{ secrets.BOX_DEVELOPER_TOKEN }}
        run: |
          node <<EOF
          const BoxSDK = require('box-node-sdk');
          const sdk = new BoxSDK({
            clientID: process.env.BOX_CLIENT_ID,
            clientSecret: process.env.BOX_CLIENT_SECRET
          });
          
          const client = sdk.getBasicClient(process.env.BOX_DEVELOPER_TOKEN);
          
          const fs = require('fs');
          const stream = fs.createReadStream('./myTest.jar');
          
          client.files.uploadFile('0', 'myTest.jar', stream)
            .then(file => console.log('File uploaded:', file))
            .catch(err => console.error('Error uploading file:', err));
          EOF
