name: Ship JAR File to Box with JWT

on:
  workflow_dispatch: 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Box SDK
        run: npm install box-node-sdk

      - name: Upload JAR file to Box
        env:
          BOX_CONFIG: ${{ secrets.BOX_CONFIG }}
        run: |
          node <<EOF
          const BoxSDK = require('box-node-sdk');
          
          // Load the Box app settings from the environment variable
          const sdk = BoxSDK.getPreconfiguredInstance(JSON.parse(process.env.BOX_CONFIG));
          
          // Authenticate the app using JWT
          const client = sdk.getAppAuthClient('enterprise');

          // Replace 'user' with 'enterprise' to use the Service Account (App User)
          const fs = require('fs');
          const stream = fs.createReadStream('./myTest.jar');

          client.files.uploadFile('0', 'myTest.jar', stream)
            .then(file => console.log('File uploaded:', file))
            .catch(err => console.error('Error uploading file:', err));
          EOF


      - name: Generate Access Token
        id: generate_token
        env:
          BOX_CONFIG: ${{ secrets.BOX_CONFIG }}  # Store Config.json content as a secret
        run: |
          node -e "
          const BoxSDK = require('box-node-sdk');
          const fs = require('fs');
          const config = JSON.parse(process.env.BOX_CONFIG);
          const sdk = BoxSDK.getPreconfiguredInstance(config);
          const client = sdk.getAppAuthClient('user', 'YOUR_USER_ID'); // Replace with your user ID
          client.getAccessToken().then(token => {
            console.log('ACCESS_TOKEN=' + token);
            fs.writeFileSync('/tmp/access_token.txt', token);
          }).catch(err => {
            console.error('Error generating access token:', err);
            process.exit(1);
          });
          "
        continue-on-error: true

      - name: Verify File Upload
        run: |
          ACCESS_TOKEN=$(cat /tmp/access_token.txt)
          curl -X GET "https://api.box.com/2.0/folders/0/items" \
               -H "Authorization: Bearer $ACCESS_TOKEN"
