name: Upload Files to Box

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload JAR to Box
        run: |
          curl -X POST "https://upload.box.com/api/2.0/files/content" \
               -H "Authorization: Bearer ${{ secrets.BOX_DEVELOPER_TOKEN }}" \
               -F "folder_id=281816790119" \
               -F "file=@./test.zip"

      - name: Upload ZIP to Bor
        run: |
          curl -X POST "https://upload.box.com/api/2.0/files/content" \
               -H "Authorization: Bearer ${{ secrets.BOX_DEVELOPER_TOKEN }}" \
               -F "folder_id=0" \
               -F "file=@./myTest.jar"
               
      - name: Validate files after uploading
        run: |
          curl -X GET "https://api.box.com/2.0/folders/281816790119/items" \
          -H "Authorization: Bearer ${{ secrets.BOX_DEVELOPER_TOKEN }}"
