name: Upload to Box jwt

on:
  workflow_dispatch:

jobs:
  upload-zip-to-box:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install "boxsdk[jwt]"

      - name: Generate Box Access Token
        run: |
          echo "${{ secrets.BOX_JWT_CONFIG }}" | base64 --decode | jq > config.json
          ACCESS_TOKEN=$(python3 - <<EOF
          from boxsdk import JWTAuth
          auth = JWTAuth.from_settings_file('config.json')
          access_token = auth.authenticate_instance()
          print(access_token)
          EOF
          )
          echo "BOX_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Upload ZIP to Box
        env:
          BOX_ACCESS_TOKEN: ${{ env.BOX_ACCESS_TOKEN }}
          BOX_FOLDER_ID: '0'
        run: |
          echo $BOX_ACCESS_TOKEN
          cd lambdas/python
          curl -X POST "https://upload.box.com/api/2.0/files/content" \
            -H "authorization: Bearer $BOX_ACCESS_TOKEN" \
            -H "content-type: multipart/form-data" \
            -F "attributes={\"name\":\"myTest.jar\", \"parent\":{\"id\":\"$BOX_FOLDER_ID\"}}" \
            -F file=@./myTest.jar
