name: Upload File to Box using access token

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List Files
      run: ls -l ./myTest.jar

    - name: Upload a File to Box
      id: upload
      run: |
        RESPONSE=$(curl -X POST https://api.box.com/2.0/files/content \
        -H "Authorization: Bearer ${{ secrets.BOX_BEARER_TOKEN }}" \
        -F "attributes={\"name\":\"myTest.jar\",\"parent\":{\"id\":\"0\"}};type=application/json" \
        -F "file=@./myTest.jar")
        echo "Response: $RESPONSE"
        echo "::set-output name=file_id::$(echo $RESPONSE | jq -r '.entries[0].id')"
    
    - name: List Files in the Folder
      run: |
        FOLDER_ID="0"  # Replace with your actual folder ID if not the root
        RESPONSE=$(curl -X GET https://api.box.com/2.0/folders/$FOLDER_ID/items \
        -H "Authorization: Bearer ${{ secrets.BOX_BEARER_TOKEN }}" \
        -H "Content-Type: application/json")
        echo "Files in Folder: $RESPONSE"

